spring:
  application:
    name: welcome-service
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/welcomedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true     # want to register this service to eureka using IP Address
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "welcome-service"
    description: "Greeting Demo Application"
    version: "1.0.0"

logging:
  level:
    com:
      app: DEBUG