services:
  # A generic network service used by other services to ensure they are in the same network
  network-deploy-service:
    networks:
      - demo-greet-welcome          # Specifies the network (demo-greet-welcome) that this service will join

  # MySQL database configuration service for microservices
  microservice-db-config:
    extends:
      service: network-deploy-service       # Extends the configuration from the network-deploy-service, ensuring network compatibility
    image: mysql      # Docker image for MySQL database
    healthcheck:      # Configures a health check for the MySQL service to ensure it's running correctly
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]    # Ping the MySQL service to check its health
      timeout: 10s # Timeout after 10 seconds if the test fails
      retries: 10  # Retry the health check 10 times if it fails
      interval: 10s  # Check every 10 seconds
      start_period: 10s   # Allow the service to start and be ready for 10 seconds before starting health checks
    environment:
      MYSQL_ROOT_PASSWORD: root

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m      # Limits the memory usage to 700MB for this service

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/      # Configures the config server URL for Spring to load configurations
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/    # Configures the eureka server URL for Spring to load configurations
